
# https://www.elastic.co/guide/en/beats/filebeat/8.16/filebeat-reference-yml.html
filebeat.inputs:

- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

  processors:
    - decode_json_fields:
        fields: ["message"]
        target: ""
        # overwrite existing target elasticsearch fields while decoding json fields
        overwrite_keys: true
    - add_docker_metadata:
        # annotates each event with relevant metadata from Docker containers
        host: "unix:///var/run/docker.sock"
    - drop_fields:
        # drop the fields below in order to have a cleaner log
        fields:
            - "container.labels"

# setup filebeat to send output to logstash
output.logstash:
  hosts: 
    - logstash

# Write Filebeat own logs only to file to avoid catching them with itself in docker log files
logging.level: debug
logging.to_files: false
logging.to_syslog: false
loggins.metrice.enabled: false
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
ssl.verification_mode: full