global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: 'ticket-producer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9080']
        labels:
          application: ticket-producer
  - job_name: 'sport-consumer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9081']
        labels:
          application: sport-ticket-consumer # spring app name not container name