apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
  - name: Prometheus-Sport-Consumer
    type: prometheus
    access: proxy
    orgId: 1
    url: http://sport-consumer:9081
    basicAuth: false
    isDefault: false
    editable: true
  - name: Prometheus-Movie-Consumer
    type: prometheus
    access: proxy
    orgId: 1
    url: http://movie-consumer:9082
    basicAuth: false
    isDefault: false
    editable: true