global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 30s

# TODO: keep this for newer image support
# otlp:
#   promote_resource_attributes:
#     - service.instance.id
#     - service.name
#     - service.namespace
#     - cloud.availability_zone
#     - cloud.region
#     - container.name
#     - deployment.environment.name

storage:
  tsdb:
    out_of_order_time_window: 30m

scrape_configs:

  - job_name: otel-collector
    static_configs:
      - targets:
        - 'otel-collector:8888'

  - job_name: 'ticket-producer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9080']
        labels:
          application: ticket-producer

  - job_name: 'sport-consumer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9081']
        labels:
          application: sport-ticket-consumer # spring app name not container name
  
  - job_name: 'movie-consumer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9082']
        labels:
          application: movie-ticket-consumer # spring app name not container name
