apiVersion: 1

datasources:
  - name: Prometheus
    uid: ticketing-metrics
    type: prometheus
    url: http://prometheus:9090
    editable: true
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: webstore-traces
          name: trace_id

        - url: http://localhost:8080/jaeger/ui/trace/$${__value.raw}
          name: trace_id
          urlDisplayLabel: View in Jaeger UI

  - name: Prometheus-Ticket-Producer
    uid: ticket-producer-metrics
    type: prometheus
    access: proxy
    orgId: 1
    url: http://ticket-producer:9080
    basicAuth: false
    isDefault: false
    editable: true

  - name: Prometheus-Sport-Consumer
    uid: sport-consumer-metrics
    type: prometheus
    access: proxy
    orgId: 1
    url: http://sport-consumer:9081
    basicAuth: false
    isDefault: false
    editable: true

  - name: Prometheus-Movie-Consumer
    uid: movie-consumer-metrics
    type: prometheus
    access: proxy
    orgId: 1
    url: http://movie-consumer:9082
    basicAuth: false
    isDefault: false
    editable: true
